apartools/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index

urlpatterns = [
    path('', index, name="index"),
    path('check-apartment/', include('check_arrangement.urls')),
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

aparttools/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index

urlpatterns = [
    path('', index, name="index"),
    path('check-apartment/', include('check_arrangement.urls')),
    path('admin/', admin.site.urls),
]

check_arrangement/urls.py
from django.urls import path

from . import views

app_name = "check_arrangement"
urlpatterns = [
    path('', views.index, name='index'),
    path('add_apartment/', views.add_apartment, name='add_apartment'),
    path('delete_apartment/<int:apartment_id>', views.delete_apartment, name='delete_apartment'),
    path('delete_issue/<int:apartmentissues_id>/', views.delete_issue, name='delete_issue'),
    path('add_issue/<int:apartment_id>/', views.add_issue, name="add_issue"),
    path('sheets/<int:apartment_id>/', views.sheets, name='sheets'),
    path('sheets/to_delivery/<int:apartment_id>/', views.to_delivery, name='to_delivery'),
    path('sheets/delivery/<int:sheet_id>/', views.delivery, name='delivery'),
    path('sheets/handled/<int:sheet_id>/', views.handled, name='handled'),
    path('sheets/unavailable/<int:sheet_id>/', views.unavailable, name='unavailable'),
    path('sheets/update_to_not_handled/<int:apartment_sheet_handled_id>/', views.update_to_not_handled, name='update_to_not_handled'),
    path('<int:apartment_id>/results/', views.results, name="results"),
]

check_arrangement/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class CustomMinValueValidator(MinValueValidator):
    def __init__(self, limit_value, message=None):
        super().__init__(limit_value, message=message or f'La valeur doit être au moins de {limit_value}.')


class CustomMaxValueValidator(MaxValueValidator):
    def __init__(self, limit_value, message=None):
        super().__init__(limit_value, message=message or f'La valeur ne peut pas dépasser {limit_value}.')


class Apartment(models.Model):

    name = models.CharField(max_length=32, unique=True, error_messages={
        'unique': 'Un appartement portant ce nom éxiste déjà.'
    }, verbose_name='Nom')
    created_at = models.DateTimeField(auto_now_add=True)
    bedroom = models.PositiveSmallIntegerField(default=1,
                                               validators=[
                                                    CustomMinValueValidator(
                                                    1,
                                                    f'Au moins 1 chambre ! On dort où sinon ?'),
                                                             CustomMaxValueValidator(12)
                                                           ],
                                               verbose_name='Chambre')
    bathroom = models.PositiveSmallIntegerField(default=1,
                                               validators=[
                                                   CustomMaxValueValidator(6)
                                               ],
                                                verbose_name='Salle de bain')
    kitchen = models.PositiveSmallIntegerField(default=1, verbose_name='Cuisine')

    class Meta:
        verbose_name = 'Appartement'
        verbose_name_plural = 'Appartements'

    # Met la première lettre du champ 'name' en majuscule
    def save(self, *args, **kwargs):
        self.name = self.name.capitalize()
        super(Apartment, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


# Permet d'ajouter des accessoires depuis le panel admin
class Sheets(models.Model):
    ROOM_CHOICES = (
        ('KITCHEN', 'Cuisine'),
        ('BEDROOM', 'Chambre'),
        ('BATHROOM', 'Salle de bain'),
        ('COMMON', 'Espaces communs')
    )
    name = models.CharField(max_length=24, unique=True, verbose_name='Nom')
    room = models.CharField(max_length=24, choices=ROOM_CHOICES,
                            default='KITCHEN', verbose_name='Pièce')

    # Met la première lettre du champ 'name' en majuscule
    def save(self, *args, **kwargs):
        self.name = self.name.capitalize()
        super(Sheets, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Accessoire'
        verbose_name_plural = 'Accessoires'

    def __str__(self):
        return self.name


class ApartmentSheets(models.Model):
    STATUS_CHOICES = [
        ('NOT_HANDLED', 'Non traité'),
        ('NOT_AVAILABLE', 'Indisponible'),
        ('HANDLED', 'Préparé'),
        ('DELIVERY', 'Livré')
    ]

    apartment = models.ForeignKey(Apartment, on_delete=models.CASCADE)
    sheet = models.ForeignKey(Sheets, on_delete=models.CASCADE)
    status = models.CharField(max_length=24, choices=STATUS_CHOICES, default='NOT_HANDLED')

    def __str__(self):
        return f"{self.sheet.name}"

    class Meta:
        unique_together = ('apartment', 'sheet')  # Chaque paire doit être unique
        verbose_name = 'Accessoire'
        verbose_name_plural = 'Accessoires'


# Permet d'ajouter des types d'incident depuis le panel admin
class IncidentType(models.Model):
    name = models.CharField(max_length=30, unique=True, verbose_name='Nom')

    class Meta:
        verbose_name = 'Incident'
        verbose_name_plural = 'Incidents'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.capitalize()
        super(IncidentType, self).save(*args, **kwargs)


class ApartmentIssues(models.Model):
    apartment = models.ForeignKey(Apartment, on_delete=models.CASCADE)
    room = models.CharField(max_length=24, verbose_name='pièce')
    incident_type = models.TextField(verbose_name='Type d\'incident')
    details = models.TextField(verbose_name='Informations complémentaires')

check_arrangement/forms.py
from django import forms
from .models import Apartment, ApartmentIssues, IncidentType, ApartmentSheets


class ApartmentForm(forms.ModelForm):
    class Meta:
        model = Apartment
        fields = ['name', 'bedroom', 'bathroom']
        labels = {
            'name': "Nom de l'appartement",
            'bedroom': 'Nombre de chambre',
            'bathroom': 'Nombre de SDB'
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control-input'}),
            'bedroom': forms.NumberInput(attrs={'class': 'form-control-input number-input'}),
            'bathroom': forms.NumberInput(attrs={'class': 'form-control-input number-input'}),
        }

    # Met la première lettre du champ 'name' en majuscule
    def clean_name(self):
        name = self.cleaned_data['name']
        return name.capitalize()


class IssuesForm(forms.ModelForm):
    class Meta:
        model = ApartmentIssues
        fields = ['room', 'incident_type', 'details']
        widgets = {
            'details': forms.Textarea(attrs={'class': 'form-text-area', 'rows': '2'})
        }

    def clean_details(self):
        details = self.cleaned_data['details']
        return details.capitalize()

    # Récupère l'instance d'appartement
    def __init__(self, *args, **kwargs):
        apartment = kwargs.pop('apartment', None)
        super(IssuesForm, self).__init__(*args, **kwargs)

        # Crée la liste rooms contenant des tuples de pièce
        if apartment:
            rooms = [('Entrée', 'Entrée'), ('Cuisine', 'Cuisine'), ('Salon', 'Salon')]
            rooms += [(f'Chambre {i}', f'Chambre {i}') for i in range(1, apartment.bedroom + 1)]
            rooms += [(f'Salle de bain {i}', f'Salle de bain {i}') for i in range(1, apartment.bathroom + 1)]
            rooms += [('Buanderie', 'Buanderie')]
            # Définit dynamiquement le champ 'room' en ChoiceField
            self.fields['room'] = forms.ChoiceField(choices=rooms, label='Pièce')

    incident_type = forms.ModelChoiceField(queryset=IncidentType.objects.all(), label="Type d'incident")


# Formulaire pr la gestion des accessoires, est-ce le bon choix ?
# Je voyais ça avec un choix multiple pour chaque accessoire,
# mon idéal était une màj automatique (sans bouton submit)
class SheetForm(forms.ModelForm):

    class Meta:
        model = ApartmentSheets
        fields = ['status']
        widgets = {
            'status': forms.Select()
        }

check_arrangement/views.py
from django.shortcuts import render, get_object_or_404, redirect
from collections import defaultdict
from .models import Apartment, ApartmentIssues, ApartmentSheets
from .forms import ApartmentForm, IssuesForm, SheetForm
from django.apps import apps
from django.urls import reverse

from . import forms


def add_apartment(request):
    if request.method == 'POST':
        form = ApartmentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('check_arrangement:index')
    else:
        form = ApartmentForm()
    return render(request, 'check_arrangement/add_apartment.html', {'form': form})


def delete_apartment(request, apartment_id):
    apartment = Apartment.objects.get(id=apartment_id)
    apartment.delete()
    return redirect('check_arrangement:index')


def delete_issue(request, apartmentissues_id):
    issue = get_object_or_404(ApartmentIssues, id=apartmentissues_id)
    issue.delete()
    return redirect('check_arrangement:results', apartment_id=issue.apartment.id)


def index(request):
    list_apartment = Apartment.objects.filter().order_by('name')
    app = apps.get_app_config('check_arrangement')
    context = {
        'list_apartment': list_apartment,
        'app': app
    }
    return render(request, "check_arrangement/index.html", context)


def add_issue(request, apartment_id):
    apartment = get_object_or_404(Apartment, id=apartment_id)
    if request.method == 'POST':
        form = IssuesForm(request.POST, apartment=apartment,)
        rendered_form = form.render("check_arrangement/forms/form_snippet.html")
        if form.is_valid():
            form.instance.apartment = apartment
            form.save()
            return redirect(f"{reverse('check_arrangement:add_issue', kwargs={'apartment_id': apartment.id})}?success=1")
    else:
        form = IssuesForm(apartment=apartment, label_suffix='')
        rendered_form = form.render("check_arrangement/forms/form_snippet.html")
    context = {
        'apartment': apartment,
        'form': rendered_form
    }

    return render(request, 'check_arrangement/add_issue.html', context)


# Vue pour la gestion des accessoires
# Récupère chaque accessoire pour distribuer aux formulaires
def sheets(request, apartment_id):
    apartment = get_object_or_404(Apartment, id=apartment_id)
    sheets = ApartmentSheets.objects.filter(apartment_id=apartment_id)
    sheets_not_handled = ApartmentSheets.objects.filter(apartment_id=apartment_id, status='NOT_HANDLED')
    sheets_handled = ApartmentSheets.objects.filter(apartment_id=apartment_id, status='HANDLED')
    sheets_delivery = ApartmentSheets.objects.filter(apartment_id=apartment_id, status='DELIVERY')
    sheets_unavailable = ApartmentSheets.objects.filter(apartment_id=apartment_id, status='NOT_AVAILABLE')

    all_sheets_handled = False

    if not sheets_not_handled:
        all_sheets_handled = True

    print(all_sheets_handled)
    context = {
     'apartment': apartment,
     'sheets':  sheets,
     'sheets_handled': sheets_handled,
     'sheets_delivery': sheets_delivery,
     'sheets_unavailable': sheets_unavailable,
     'all_sheets_handled': all_sheets_handled
    }

    return render(request, 'check_arrangement/sheets.html', context)


def delivery(request, sheet_id):
    sheet = ApartmentSheets.objects.filter(id=sheet_id)
    apartment_id = sheet.values()[0]['apartment_id']
    sheet.update(status='DELIVERY')
    return redirect('check_arrangement:sheets', apartment_id=apartment_id)


def handled(request, sheet_id):
    sheet = ApartmentSheets.objects.filter(id=sheet_id)
    apartment_id = sheet.values()[0]['apartment_id']
    sheet.update(status='HANDLED')
    return redirect('check_arrangement:sheets', apartment_id=apartment_id)


def unavailable(request, sheet_id):
    sheet = ApartmentSheets.objects.filter(id=sheet_id)
    apartment_id = sheet.values()[0]['apartment_id']
    sheet.update(status='NOT_AVAILABLE')
    return redirect('check_arrangement:sheets', apartment_id=apartment_id)


def to_delivery(request, apartment_id):
    sheets_handled = ApartmentSheets.objects.filter(apartment_id=apartment_id, status='HANDLED')
    sheets_handled.update(status='DELIVERY')
    return redirect('check_arrangement:sheets', apartment_id=apartment_id)


def update_to_not_handled(request, apartment_sheet_handled_id):
    apartment_sheet_handled = ApartmentSheets.objects.filter(id=apartment_sheet_handled_id)
    apartment_id = apartment_sheet_handled.values()[0]['apartment_id']  # Recup l'id de l'appart
    apartment_sheet_handled.update(status='NOT_HANDLED')
    return redirect('check_arrangement:sheets', apartment_id=apartment_id)


# Vue permettant de voir les incidents qui ont été ajoutés pour l'appartement sélectionné
def results(request, apartment_id):
    apartment = get_object_or_404(Apartment, id=apartment_id)
    apartment_issues = ApartmentIssues.objects.filter(apartment_id=apartment_id)
    apartment_sheets = ApartmentSheets.objects.filter(apartment_id=apartment_id)
    status_choices = ApartmentSheets.STATUS_CHOICES

    # Initialisation du dictionnaire pour les incidents
    apartment_issues_dict = defaultdict(lambda: defaultdict(list))
    # Ajoute incidents présent dans le dict
    for issue in apartment_issues:
        room = issue.room
        incident_type = issue.incident_type
        details = issue.details

        apartment_issues_dict[room][incident_type].append((details, issue.id))
    # Conversion en dict normal
    apartment_issues_dict = {room: dict(issues) for room, issues in apartment_issues_dict.items()}

    apartment_sheets_dict = defaultdict(list)

    for sheet in apartment_sheets:
        apartment_sheets_dict[sheet.status].append(sheet)

    apartment_sheets_dict = dict(apartment_sheets_dict)

    apartment_sheets = {value: apartment_sheets_dict.get(key, []) for key, value in status_choices}

    context = {
        'apartment': apartment,
        'apartment_issues_dict': apartment_issues_dict,
        'apartment_sheets': apartment_sheets
    }
    return render(request, 'check_arrangement/results.html', context)

check_arrangement/templates/check_arrangement/add_apartment.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Ajouter un appartement</title>
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="{% static 'check_arrangement/style/build.css' %}">
    <script src="{% static 'check_arrangement/js/forms.js' %}" defer></script>
</head>
<body class="h-full bg-gray-50 text-gray-800">
    <a href="{% url 'index' %}" class="breadcrumb">Liste des outils</a>
    <a href="{% url 'check_arrangement:index' %}" class="breadcrumb">Liste des appartements</a>
    <div class="max-w-xl mx-auto p-4 flex flex-col items-center">
        <p class="text-2xl font-semibold mb-8 text-center">Ajouter un nouvel appartement</p>
        <form class='form-add' method="POST">
            {% csrf_token %}
            {{ form }}
            <ul class="flex w-full justify-between mt-16">
                <li class="flex">
                    <a href="{% url 'check_arrangement:index' %}" class="btn-cancel">Annuler</a>
                </li>
                <li>
                    <button type="submit" class="btn-add self-center" title="Ajouter appartement">Ajouter appartement</button>
                </li>
            </ul>
        </form>
    </div>
</body>
</html>

check_arrangement/templates/check_arrangement/add_issue.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ apartment.name }} - Ajouter incident</title>
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="{% static 'check_arrangement/style/style_output.css' %}">
    <script src="{% static 'check_arrangement/js/forms.js' %}" defer></script>
</head>
<body>
    <a href="{% url 'index' %}" class="breadcrumb">Liste des outils</a>
    <a href="{% url 'check_arrangement:index' %}" class="breadcrumb">Liste des appartements</a>
    <div class="main">
        <div class="container card-head-apart">
            <h1 class="card-head-apart-name">{{ apartment.name }}</h1>
            <div class="card-head-apart-col-label">
                <ul>
                    <li class="card-label">{{ apartment.bedroom }} chambre{{ apartment.bedroom|pluralize }}</li>
                    <li class="card-label">{{ apartment.bathroom }} salle{{ apartment.bathroom|pluralize }} de bain</li>
                </ul>
                <p class="text-base font-normal text-xs">Ajouté le {{ apartment.created_at|date:'d F Y à H:i' }}</p>
            </div>
            <div class="card-head-apart-col-btn">
                <a class="btn secondary-btn" href="{% url 'check_arrangement:results' apartment.id %}">Fiche appart</a>
            </div>
        </div>
        <h2 class="title-category">Renseigner un incident</h2>
        <form class='form-add-issue' method="POST">
        {% csrf_token %}
            {{ form }}
            <div class="w-full flex justify-center mt-6">
                <button class="btn primary-btn" type="submit" title="Ajouter incident">Ajouter incident</button>
            </div>
        </form>
    <div id="add-issue-modal-success" class="modal-success-issue">Incident Ajoutée !</div>
    </div>
    </div>
</body>
</html>

check_arrangement/templates/check_arrangement/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="h-full">
<head>
    <meta charset="UTF-8">
    <title>Liste apparts</title>
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="{% static 'check_arrangement/style/style_output.css' %}">
    <script src="{% static 'check_arrangement/js/modal.js' %}" defer></script>
</head>
<body class="h-full bg-gray-50 text-gray-800">
    <a href="{% url 'index' %}" class="breadcrumb">Les outils</a>
    <div class="max-w-xl mx-auto p-4 flex flex-col items-center">
        <p class="text-2xl font-semibold mb-8 text-center">{{ app.verbose_name }}</p>
        {% if list_apartment %}
        {% for apartment in list_apartment %}
        <div class="card-apart-head">
            {{ apartment.name }}
        </div>
        {% endfor %}
            <table class="table-auto max-w-xl w-full">
                <thead>
                    <tr>
                        <th class="">Nom</th>
                        <th class="">Chambres</th>
                        <th class="">SDB</th>
                        <th class="">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for apartment in list_apartment %}
                    <tr>
                        <td class="py-2 text-center"><a href="{% url 'check_arrangement:results' apartment.id %}" class="btn-access-table">{{ apartment.name }}</a></td>
                        <td class="py-2 text-center"><span>{{ apartment.bedroom }}</span></td>
                        <td class="py-2 text-center"><span>{{ apartment.bathroom }}</span></td>
                        <td class="py-2 flex justify-center gap-3">
                            <a class="cursor-pointer" href="{% url 'check_arrangement:add_issue' apartment.id %}" title="Ajouter incident">🔨</a>
                            <a class="cursor-pointer" href="{% url 'check_arrangement:sheets' apartment.id %}" title="Check list des accessoires">📑</a>
                            <button class="btn-delete" title="Supprimer" data-id="{{ apartment.id }}">❌</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p class="mt-10">Aucun appartement enregistré pour le moment...</p>
        {% endif %}
        <div id="addModal" class="modal" style="display: none;">
            <div class="modal-content max-w-xl">
                <span class="close-add">&times;</span>

                <div class="flex justify-around mt-4">
                    <button id="confirmAdd" class="text-red-600 font-medium w-1/2">Ajouter</button>
                </div>
            </div>
        </div>
        <div id="deleteModal" class="modal" style="display: none;">
            <div class="modal-content max-w-xl">
                <span class="close-delete">&times;</span>
                <p class="pt-4 sm:pt-0">Êtes-vous sûr de vouloir supprimer cet appartement ?</p>
                <div class="flex justify-around mt-4">
                    <button id="confirmDelete" class="text-red-600 font-medium w-1/2">Oui</button>
                    <button id="cancelDelete" class="w-1/2 font-medium">Non</button>
                </div>
            </div>
        </div>
        <a href="{% url 'check_arrangement:add_apartment' %}"
           id="btn-add" class="btn-add mt-20">Ajouter un appartement</a>
    </div>

</body>
</html>

check_arrangement/templates/check_arrangement/results.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{ apartment.name }}</title>
  <meta name="viewport" content="width=device-width">
  <link rel="stylesheet" href="{% static 'check_arrangement/style/style_output.css' %}">
</head>
<body>
  <a href="{% url 'index' %}" class="breadcrumb">Les outils</a>
  <a href="{% url 'check_arrangement:index' %}" class="breadcrumb">Les apparts</a>
  <div class="main">
    <div class="container card-head-apart">
        <h1 class="card-head-apart-name">{{ apartment.name }}</h1>
        <div class="card-head-apart-col-label">
          <ul>
            <li class="card-label">{{ apartment.bedroom }} chambre{{ apartment.bedroom|pluralize }}</li>
            <li class="card-label">{{ apartment.bathroom }} salle{{ apartment.bathroom|pluralize }} de bain</li>
          </ul>
          <p class="text-base font-normal text-xs">Ajouté le {{ apartment.created_at|date:'d F Y à H:i' }}</p>
        </div>
        <div class="card-head-apart-col-btn">
         <a class="btn secondary-btn"
             href="{% url 'check_arrangement:add_issue' apartment.id %}">Ajouter incidents</a>
          <a class="btn secondary-btn"
             href="{% url 'check_arrangement:sheets' apartment.id %}">Les accessoires</a>
        </div>
    </div>
    {% if apartment_issues_dict %}
    <h2 class="title-category">Liste des incidents</h2>
    <div class="border rounded-md overflow-hidden w-full">
      <table class="w-full text-sm bg-white md:text-base">
      <thead>
        <tr class="text-lg">
          <th class="md:px-4 md:py-2 p-1 text-left">Pièce</th>
          <th class="md:px-4 md:py-2 p-1 text-left">Type</th>
          <th class="md:px-4 md:py-2 p-1 text-left">Détails</th>
          <th class="md:px-4 md:py-2 p-1 text-left">Actions</th>
        </tr>
      </thead>
      {% for room, issues in apartment_issues_dict.items %}
      {% for incident_type, details_list in issues.items %}
      {% for detail, issue_id in details_list %}
      <tbody>
        <tr>
          <th class="md:px-4 md:py-2 p-1 text-left border-t">{{ room }}</th>
          <td class="md:px-4 md:py-2 p-1 border-t">{{ incident_type }}</td>
          <td class="md:px-4 md:py-2 p-1 border-t">{{ detail }}</td>
          <td class="md:px-4 md:py-2 p-1 text-center border-t"><a href="{% url 'check_arrangement:delete_issue' issue_id %}" title="Supprimer l'incident">❌</a></td>
        </tr>
      </tbody>
      {% endfor %}
      {% endfor %}
      {% endfor %}
    </table>
    </div>
    {% endif %}
    <div class="w-full">
      <h2 class="title-category">Liste des accessoires</h2>
      <div class="grid grid-cols-2 grid-rows-2 md:grid-cols-4 gap-4">
        {% for status, sheets in apartment_sheets.items %}
        <div class="border h-fit border-gray-200 rounded-md overflow-hidden">
          <table class="w-full text-sm bg-white md:text-base">
            <thead>
             <tr class="text-lg">
               <th class="md:px-4 md:py-2 p-1 text-left">
                 {{ status }}
               </th>
             </tr>
            </thead>
            {% if sheets %}
            <tbody>
              {% for sheet in sheets %}
              <tr>
                <td class="md:px-4 md:py-2 p-1 border-t">{{ sheet }}</td>
              </tr>
              {% endfor %}
            </tbody>
              {% else %}
              <tbody>
                <tr>
                  <td class="md:px-4 md:py-2 p-1 border-t">Non renseigné</td>
                </tr>
              </tbody>
            {% endif %}
          </table>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>


</body>
</html>

check_arrangement/templates/check_arrangement/sheets.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{ apartment.name }} - Accessoires</title>
  <meta name="viewport" content="width=device-width">
  <link rel="stylesheet" href="{% static 'check_arrangement/style/style_output.css' %}">
</head>
<body class="h-full bg-gray-50 text-gray-800">
  <a href="{% url 'index' %}" class="breadcrumb">Les outils</a>
  <a href="{% url 'check_arrangement:index' %}" class="breadcrumb">Les apparts</a>
  <div class="main">
    <div class="container card-head-apart">
            <h1 class="card-head-apart-name">{{ apartment.name }}</h1>
            <div class="card-head-apart-col-label">
                <ul>
                    <li class="card-label">{{ apartment.bedroom }} chambre{{ apartment.bedroom|pluralize }}</li>
                    <li class="card-label">{{ apartment.bathroom }} salle{{ apartment.bathroom|pluralize }} de bain</li>
                </ul>
                <p class="text-base font-normal text-xs">Ajouté le {{ apartment.created_at|date:'d F Y à H:i' }}</p>
            </div>
            <div class="card-head-apart-col-btn">
                <a class="btn secondary-btn" href="{% url 'check_arrangement:results' apartment.id %}">Fiche appart</a>
            </div>
        </div>
    <h2 class="title-category">Les accessoires nécessaires</h2>
    <div class="w-full md:max-w-xl flex flex-col gap-8">
      <div class="container">
        {% for sheet in sheets %}
          {% if sheet.status == 'NOT_HANDLED' %}
            <div class="flex flex-col gap-2">
              <h3 class="text-xl self-center">{{ sheet }}</h3>
              <div class="flex w-full justify-between gap-2 mb-6">
                <a class='btn secondary-btn w-1/3' href="{% url 'check_arrangement:handled' sheet.id %}">Préparé</a>
                <a class='btn secondary-btn w-1/3' href="{% url 'check_arrangement:delivery' sheet.id %}">Livré</a>
                <a class='btn secondary-btn w-1/3' href="{% url 'check_arrangement:unavailable' sheet.id %}">Indisponible</a>
              </div>
            </div>
          {% endif %}
        {% endfor %}
        {% if all_sheets_handled %}
          <p class="text-center">Tous les accessoires ont été traités 👍</p>
        {% endif %}
      </div>
      {% if sheets_handled %}
      <div class="container flex flex-col gap-2">
        <h3 class="text-xl mb-2">Accessoires prêts pour être livrés</h3>
        {% for sheet in sheets_handled %}
          <ul>
            <li class="flex justify-between border-b">
              {{ sheet }}
              <a href="{% url 'check_arrangement:update_to_not_handled' sheet.id %}">❌</a>
            </li>
          </ul>
        {% endfor %}
        <div class="my-4 md:mb-0 self-center">
          <a class="btn primary-btn" href="{% url 'check_arrangement:to_delivery' apartment.id %}">Définir le tout comme livré</a>
        </div>
      </div>
      {% endif %}

      {% if sheets_delivery %}
      <div class="container">
        <h3 class="text-xl mb-2">Accessoires déjà livrés</h3>
          {% for sheet in sheets_delivery %}
            <ul>
              <li class="flex justify-between border-b">
                {{ sheet }}
                <a href="{% url 'check_arrangement:update_to_not_handled' sheet.id %}">❌</a>
              </li>
            </ul>
          {% endfor %}
      </div>
      {% endif %}

      {% if sheets_unavailable %}
      <div class="container">
        <h3 class="text-xl">Accessoires indisponible</h3>
          {% for sheet in sheets_unavailable %}
            <ul>
              <li class="flex justify-between border-b">
                {{ sheet }}
                <a href="{% url 'check_arrangement:update_to_not_handled' sheet.id %}" title="Non traité">❌</a>
              </li>
            </ul>
          {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</body>
</html>